services:
  Chatbot_model:
    image: rag # tên của image ởp hần Dockerfile
    container_name: call_LLMs
     # dấu - là list nhưng của Docker, là quy định trong các phần như ports, networks, depend,... 
