services:
  # --- Dịch vụ Backend (Web1) ---
  ai_api:
    build: 
      context: . 
      dockerfile: ai_api/backend/Dockerfile
    container_name: rag_ai_api
    depends_on:
      - chroma
    ports:
      - "8001:8000"
    volumes:
      - ./ai_api/backend:/app
      # Đồng bộ folder volumes để code Python tìm thấy file .db và uploads
      - ./infrastructure/volumes:/infrastructure/volumes
    working_dir: /app
    networks:
      - rag_network

  # --- Dịch vụ Database Vector ---
  chroma:
    image: chromadb/chroma:latest
    container_name: rag_chroma
    volumes:
      - ./infrastructure/volumes/chroma_data:/chroma/chroma
    ports:
      - "8000:8000" 
    networks:
      - rag_network

  # --- Dịch vụ Nạp dữ liệu (AI1 - Ingestion) ---
  ingestion:
    build: 
      context: .
      dockerfile: ingestion/Ingestion Main/Dockerfile # Chỉ đúng đường dẫn Dockerfile
    container_name: rag_ingestion
    depends_on:
      - chroma
    volumes:
      - ./ingestion/Ingestion Main:/app
      # AI1 cần đọc file từ volumes để băm nhỏ dữ liệu
      - ./infrastructure/volumes:/infrastructure/volumes
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge