# 1. Base Image
FROM python:3.10-slim

# 2. Thư mục làm việc
WORKDIR /app

# 3. Copy file môi trường
COPY requirements.txt .

# 4. Cài đặt thư viện
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copy mã nguồn
COPY rag/ ./rag/

# 6. Khai báo cổng
EXPOSE 8501

# 7. Lệnh chạy
CMD ["streamlit", "run", "rag/pages/app.py", "--server.port=8501", "--server.address=0.0.0.0"]